# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-02-06 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactwel', '0002_auto_20200205_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractwelUserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=64)),
                ('role_description', models.CharField(max_length=256)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.IntractwelUser')),
            ],
            options={
                'verbose_name': 'Interactwel Role Mapping',
                'verbose_name_plural': 'Interactwel Role Mappings',
                'db_table': 'interactwel_role_mapping',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='interactweluserrole',
            unique_together=set([('user_id', 'role_name')]),
        ),
    ]
