# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-02-06 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactwel', '0003_auto_20200206_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractwelAdaptationStory',
            fields=[
                ('story_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Interactwel Adaptation Stories',
                'verbose_name_plural': 'Interactwel Adaptation Stories',
                'db_table': 'interactwel_sdaptation_story',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InteractwelDocumentation',
            fields=[
                ('doc_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('data', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Interactwel Documentation',
                'verbose_name_plural': 'Interactwel Documentation',
                'db_table': 'interactwel_documentation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InteractwelInstructionalVideo',
            fields=[
                ('video_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Interactwel Videos',
                'verbose_name_plural': 'Interactwel Videos',
                'db_table': 'interactwel_vidos',
                'managed': True,
            },
        ),
    ]
