# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-02-06 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactwel', '0004_interactweladaptationstory_interactweldocumentation_interactwelinstructionalvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractwelGroup',
            fields=[
                ('group_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=64)),
                ('group_description', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Interactwel Group',
                'verbose_name_plural': 'Interactwel Group',
                'db_table': 'interactwel_group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InteractwelGroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelGroup')),
            ],
        ),
        migrations.CreateModel(
            name='InteractwelGroupRoleMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelGroup')),
            ],
        ),
        migrations.CreateModel(
            name='InteractwelRole',
            fields=[
                ('role_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=64)),
                ('role_description', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Interactwel Role',
                'verbose_name_plural': 'Interactwel Role',
                'db_table': 'interactwel_role',
                'managed': True,
            },
        ),
        migrations.RenameModel(
            old_name='IntractwelUser',
            new_name='InteractwelUser',
        ),
        migrations.AlterUniqueTogether(
            name='interactweluserrole',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='interactweluserrole',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='InteractwelUserRole',
        ),
        migrations.AlterUniqueTogether(
            name='interactwelrole',
            unique_together=set([('role_name',)]),
        ),
        migrations.AddField(
            model_name='interactwelgrouprolemapping',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelRole'),
        ),
        migrations.AddField(
            model_name='interactwelgroupmembership',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelUser'),
        ),
        migrations.AlterUniqueTogether(
            name='interactwelgroup',
            unique_together=set([('group_name',)]),
        ),
    ]
