# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-02-06 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactwel', '0005_auto_20200206_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractwelEvent',
            fields=[
                ('event_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=256)),
                ('event_description', models.CharField(max_length=256)),
                ('event_date', models.DateTimeField()),
                ('even_location', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Interactwel Event',
                'verbose_name_plural': 'Interactwel Event',
                'db_table': 'interactwel_event',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InteractwelEventAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelEvent')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelUser')),
            ],
            options={
                'verbose_name': 'Interactwel Event Attendence',
                'verbose_name_plural': 'Interactwel Event Attendance',
                'db_table': 'interactwel_event_attendence',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InteractwelInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_status', models.CharField(max_length=256)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelEvent')),
                ('invitee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitee_id', to='interactwel.InteractwelUser')),
                ('inviter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter_id', to='interactwel.InteractwelUser')),
            ],
            options={
                'verbose_name': 'Interactwel Invitation',
                'verbose_name_plural': 'Interactwel Invitation',
                'db_table': 'interactwel_invitation',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='interactwelgroupmembership',
            options={'managed': True, 'verbose_name': 'Interactwel Group Membership', 'verbose_name_plural': 'Interactwel Group Membership'},
        ),
        migrations.AlterModelOptions(
            name='interactwelgrouprolemapping',
            options={'managed': True, 'verbose_name': 'Interactwel Group Role Mapping', 'verbose_name_plural': 'Interactwel Group Role Mapping'},
        ),
        migrations.AlterUniqueTogether(
            name='interactwelgroupmembership',
            unique_together=set([('group_id', 'user_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='interactwelgrouprolemapping',
            unique_together=set([('group_id', 'role_id')]),
        ),
        migrations.AlterModelTable(
            name='interactwelgroupmembership',
            table='interactwel_group_membership',
        ),
        migrations.AlterModelTable(
            name='interactwelgrouprolemapping',
            table='interactwel_group_role_mapping',
        ),
        migrations.AlterUniqueTogether(
            name='interactwelinvitation',
            unique_together=set([('event_id', 'inviter_id', 'invitee_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='interactweleventattendance',
            unique_together=set([('event_id', 'user_id')]),
        ),
    ]
