# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-02-06 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactwel', '0006_auto_20200206_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractwelAction',
            fields=[
                ('action_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Interactwel Action',
                'verbose_name_plural': 'Interactwel Action',
                'db_table': 'interactwel_action',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InteractwelActor',
            fields=[
                ('actor_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Interactwel Actor',
                'verbose_name_plural': 'Interactwel Actor',
                'db_table': 'interactwel_actor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InteractwelFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('feasibilty', models.CharField(max_length=256)),
                ('comments', models.CharField(max_length=256)),
                ('q1', models.CharField(max_length=1024)),
                ('q2', models.CharField(max_length=1024)),
                ('q3', models.CharField(max_length=1024)),
                ('q4', models.CharField(max_length=1024)),
                ('rating', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Interactwel Feedback',
                'verbose_name_plural': 'Interactwel Feedback',
                'db_table': 'interactwel_feedback',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InteractwelGoal',
            fields=[
                ('goal_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Interactwel Goal',
                'verbose_name_plural': 'Interactwel Goal',
                'db_table': 'interactwel_goal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InteractwelPlan',
            fields=[
                ('plan_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Interactwel Plan',
                'verbose_name_plural': 'Interactwel Plan',
                'db_table': 'interactwel_plan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InteractwelProject',
            fields=[
                ('project_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('latitude', models.CharField(max_length=256)),
                ('longtitude', models.CharField(max_length=256)),
                ('feedbackProvided', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Interactwel Project',
                'verbose_name_plural': 'Interactwel Project',
                'db_table': 'interactwel_project',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InteractwelProjectAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelAction')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelProject')),
            ],
            options={
                'verbose_name': 'Interactwel Project Action',
                'verbose_name_plural': 'Interactwel Project Action',
                'db_table': 'interactwel_project_action',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InteractwelProjectActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelActor')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelProject')),
            ],
            options={
                'verbose_name': 'Interactwel Project Actor',
                'verbose_name_plural': 'Interactwel Project Actor',
                'db_table': 'interactwel_project_actor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InteractwelProjectGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelGoal')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelProject')),
            ],
            options={
                'verbose_name': 'Interactwel Project Goal',
                'verbose_name_plural': 'Interactwel Project Goal',
                'db_table': 'interactwel_project_goal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InteractwelProjectPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelPlan')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelProject')),
            ],
            options={
                'verbose_name': 'Interactwel Project Plan',
                'verbose_name_plural': 'Interactwel Project Plan',
                'db_table': 'interactwel_project_plan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InteractwelProjectQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelProject')),
            ],
            options={
                'verbose_name': 'Interactwel Project Question',
                'verbose_name_plural': 'Interactwel Project Question',
                'db_table': 'interactwel_project_question',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InteractwelProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=256)),
                ('role', models.CharField(max_length=256)),
                ('sector', models.CharField(max_length=256)),
                ('actor', models.CharField(max_length=256)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelProject')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelUser')),
            ],
            options={
                'verbose_name': 'Interactwel Project User',
                'verbose_name_plural': 'Interactwel Project User',
                'db_table': 'interactwel_project_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InteractwelQuestion',
            fields=[
                ('question_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=256)),
                ('question_type', models.CharField(max_length=256)),
                ('question_text', models.CharField(max_length=1024)),
                ('possible_answers', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name': 'Interactwel Question',
                'verbose_name_plural': 'Interactwel Question',
                'db_table': 'interactwel_question',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='interactwelprojectquestion',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelQuestion'),
        ),
        migrations.AddField(
            model_name='interactwelfeedback',
            name='plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelPlan'),
        ),
        migrations.AddField(
            model_name='interactwelfeedback',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelProject'),
        ),
        migrations.AddField(
            model_name='interactwelfeedback',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelUser'),
        ),
        migrations.AlterUniqueTogether(
            name='interactwelprojectuser',
            unique_together=set([('user_id', 'project_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='interactwelprojectquestion',
            unique_together=set([('project_id', 'question_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='interactwelprojectplan',
            unique_together=set([('project_id', 'plan_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='interactwelprojectgoal',
            unique_together=set([('project_id', 'goal_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='interactwelprojectactor',
            unique_together=set([('project_id', 'actor_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='interactwelprojectaction',
            unique_together=set([('project_id', 'action_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='interactwelfeedback',
            unique_together=set([('user_id', 'project_id', 'plan_id')]),
        ),
    ]
