# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-02 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactwel', '0007_auto_20200206_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactwelplan',
            name='goals',
            field=models.ManyToManyField(blank=True, related_name='plans', to='interactwel.InteractwelGoal'),
        ),
    ]
