# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-02 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactwel', '0008_interactwelplan_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactwelplan',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelProject'),
            preserve_default=False,
        ),
    ]
