# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-02 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactwel', '0010_interactwelplan_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactwelplan',
            name='actions',
            field=models.ManyToManyField(blank=True, related_name='actions', to='interactwel.InteractwelAction'),
        ),
    ]
