# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-02 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactwel', '0012_interactwelplan_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactwelplan',
            name='description',
        ),
    ]
