# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-29 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactwel', '0015_auto_20200615_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactwelfeedback',
            name='id',
        ),
        migrations.RemoveField(
            model_name='interactwelfeedback',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='interactwelfeedback',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='interactwelfeedback',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='interactwelfeedback',
            name='q4',
        ),
        migrations.AddField(
            model_name='interactwelfeedback',
            name='feedback_id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
