# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-29 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactwel', '0016_auto_20200629_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractwelFeedbackQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1024)),
                ('feedback_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelFeedback')),
            ],
            options={
                'verbose_name': 'Interactwel Feedback Question',
                'verbose_name_plural': 'Interactwel Feedback Question',
                'db_table': 'interactwel_feedback_question',
                'managed': True,
            },
        ),
    ]
