# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-11 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactwel', '0017_interactwelfeedbackquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactwelfeedbackquestion',
            name='feedback_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interactwel.InteractwelFeedback'),
        ),
    ]
