# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-11 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactwel', '0018_auto_20200711_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractwelFeedbackAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1024)),
                ('answer', models.CharField(max_length=1024)),
                ('feedback_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_answers', to='interactwel.InteractwelFeedback')),
            ],
            options={
                'verbose_name': 'Interactwel Feedback Answer',
                'verbose_name_plural': 'Interactwel Feedback Answer',
                'db_table': 'interactwel_feedback_answer',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='interactwelfeedbackquestion',
            name='feedback_id',
        ),
        migrations.DeleteModel(
            name='InteractwelFeedbackQuestion',
        ),
    ]
