# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-21 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactwel', '0019_auto_20200711_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactwelfeedback',
            name='comments',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='interactwelfeedback',
            name='rating',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
