# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-14 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactwel', '0020_auto_20200721_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactwelplan',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelUser'),
            preserve_default=False,
        ),
    ]
