# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-28 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactwel', '0022_auto_20200921_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactwelfeedback',
            name='comments',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
