# Generated by Django 2.2.17 on 2020-11-26 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactwel', '0023_auto_20200928_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractwelUserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelRole')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelUser')),
            ],
            options={
                'verbose_name': 'Interactwel User Role',
                'verbose_name_plural': 'Interactwel User Role',
                'db_table': 'interactwel_user_role',
                'managed': True,
                'unique_together': {('user_id', 'role_id')},
            },
        ),
    ]
