# Generated by Django 2.2.17 on 2021-01-07 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactwel', '0024_interactweluserrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactwelinvitation',
            name='group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelGroup'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='interactwelinvitation',
            unique_together={('event_id', 'inviter_id', 'invitee_id', 'group_id')},
        ),
    ]
