# Generated by Django 2.2.17 on 2021-01-08 01:11

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('interactwel', '0026_interactwelprojectjoinrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactwelplan',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='interactwelplan',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='interactwelplan',
            name='user_id',
        ),
        migrations.AddField(
            model_name='interactwelplan',
            name='plan_json',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='interactwelplanactoractions',
            unique_together={('actor_id', 'action_id')},
        ),
        migrations.CreateModel(
            name='InteractwelSelectedPlan',
            fields=[
                ('selected_plan_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('goals', models.ManyToManyField(blank=True, related_name='plans', to='interactwel.InteractwelGoal')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelPlan')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelProject')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelUser')),
            ],
            options={
                'verbose_name': 'Interactwel Selected Plan',
                'verbose_name_plural': 'Interactwel Selected Plan',
                'db_table': 'interactwel_selected_plan',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='interactwelplanactoractions',
            name='plan_id',
        ),
    ]
