# Generated by Django 2.2.17 on 2021-01-08 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactwel', '0027_auto_20210108_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactwelplanactoractions',
            name='selected_plan_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelSelectedPlan'),
            preserve_default=False,
        ),
    ]
