# Generated by Django 2.2.17 on 2021-01-08 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactwel', '0028_interactwelplanactoractions_selected_plan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactwelselectedplan',
            name='project_id',
        ),
    ]
