# Generated by Django 2.2.17 on 2021-01-08 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactwel', '0029_remove_interactwelselectedplan_project_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interactwelplanactoractions',
            unique_together={('actor_id', 'action_id', 'selected_plan_id')},
        ),
    ]
