# Generated by Django 2.2.17 on 2021-01-08 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactwel', '0030_auto_20210108_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactwelprojectplan',
            name='selected_plan_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interactwel.InteractwelSelectedPlan'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='interactwelprojectplan',
            unique_together={('project_id', 'selected_plan_id')},
        ),
        migrations.RemoveField(
            model_name='interactwelprojectplan',
            name='plan_id',
        ),
    ]
